# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Curated catalog of chart types for AI agent consumption."""

from __future__ import annotations

from superset.ai.chart_types.schema import ChartTypeDescriptor, ParamDescriptor

CATALOG: dict[str, ChartTypeDescriptor] = {
    # ── 时序类 ──────────────────────────────────────────────
    "echarts_timeseries_line": ChartTypeDescriptor(
        viz_type="echarts_timeseries_line",
        display_name="折线图",
        category="timeseries",
        description="展示数值随时间变化的趋势",
        best_for=["时间趋势", "连续数据变化", "多系列对比趋势"],
        not_for=["分类对比", "占比分析", "无时间维度数据"],
        params=[
            ParamDescriptor(name="granularity_sqla", type="string", required=True, description="时间列名"),
            ParamDescriptor(name="metrics", type="metric_array", required=True, description="数值指标列表"),
            ParamDescriptor(name="groupby", type="string_array", required=False, description="分组列（不同颜色的线）", default=[]),
            ParamDescriptor(name="time_range", type="string", required=False, description="时间范围", default="100 years ago : now"),
        ],
        example_form_data={"granularity_sqla": "date_col", "metrics": ["SUM(value)"], "groupby": [], "time_range": "100 years ago : now"},
        uses_metric_singular=False,
        requires_time_column=True,
        max_groupby_dimensions=3,
        default_width=6,
    ),
    "echarts_timeseries_bar": ChartTypeDescriptor(
        viz_type="echarts_timeseries_bar",
        display_name="柱状图",
        category="timeseries",
        description="用柱形高度比较不同类别的数值大小，也支持时间轴",
        best_for=["分类数值对比", "排名", "时间轴柱形"],
        not_for=["占比分析", "连续趋势（用折线）"],
        params=[
            ParamDescriptor(name="x_axis", type="string", required=True, description="X轴分类列名"),
            ParamDescriptor(name="metrics", type="metric_array", required=True, description="数值指标列表"),
            ParamDescriptor(name="groupby", type="string_array", required=False, description="分组列（堆叠系列）", default=[]),
        ],
        example_form_data={"x_axis": "category", "metrics": ["SUM(value)"], "groupby": []},
        uses_metric_singular=False,
        requires_time_column=False,
        max_groupby_dimensions=2,
        default_width=6,
    ),
    "echarts_timeseries_smooth": ChartTypeDescriptor(
        viz_type="echarts_timeseries_smooth",
        display_name="平滑折线图",
        category="timeseries",
        description="平滑曲线展示数值随时间变化的趋势",
        best_for=["趋势平滑展示", "曲线拟合"],
        not_for=["分类对比", "精确数值"],
        params=[
            ParamDescriptor(name="granularity_sqla", type="string", required=True, description="时间列名"),
            ParamDescriptor(name="metrics", type="metric_array", required=True, description="数值指标列表"),
            ParamDescriptor(name="groupby", type="string_array", required=False, description="分组列", default=[]),
            ParamDescriptor(name="time_range", type="string", required=False, description="时间范围", default="100 years ago : now"),
        ],
        example_form_data={"granularity_sqla": "date_col", "metrics": ["SUM(value)"], "groupby": [], "time_range": "100 years ago : now"},
        uses_metric_singular=False,
        requires_time_column=True,
        max_groupby_dimensions=3,
        default_width=6,
    ),
    "echarts_area": ChartTypeDescriptor(
        viz_type="echarts_area",
        display_name="面积图",
        category="timeseries",
        description="用填充面积展示数值随时间变化的趋势，支持堆叠",
        best_for=["趋势+面积感", "堆叠总量展示", "组成随时间变化"],
        not_for=["分类对比", "精确数值"],
        params=[
            ParamDescriptor(name="granularity_sqla", type="string", required=True, description="时间列名"),
            ParamDescriptor(name="metrics", type="metric_array", required=True, description="数值指标列表"),
            ParamDescriptor(name="groupby", type="string_array", required=False, description="分组列（堆叠面积）", default=[]),
            ParamDescriptor(name="time_range", type="string", required=False, description="时间范围", default="100 years ago : now"),
        ],
        example_form_data={"granularity_sqla": "date_col", "metrics": ["SUM(value)"], "groupby": ["series_col"], "time_range": "100 years ago : now"},
        uses_metric_singular=False,
        requires_time_column=True,
        max_groupby_dimensions=3,
        default_width=6,
    ),
    "echarts_timeseries_step": ChartTypeDescriptor(
        viz_type="echarts_timeseries_step",
        display_name="阶梯图",
        category="timeseries",
        description="以阶梯形式展示数值随时间的变化，适合离散跳变数据",
        best_for=["阶梯型变化", "状态切换", "离散时间数据"],
        not_for=["连续趋势", "分类对比"],
        params=[
            ParamDescriptor(name="granularity_sqla", type="string", required=True, description="时间列名"),
            ParamDescriptor(name="metrics", type="metric_array", required=True, description="数值指标列表"),
            ParamDescriptor(name="groupby", type="string_array", required=False, description="分组列", default=[]),
            ParamDescriptor(name="time_range", type="string", required=False, description="时间范围", default="100 years ago : now"),
        ],
        example_form_data={"granularity_sqla": "date_col", "metrics": ["SUM(value)"], "groupby": [], "time_range": "100 years ago : now"},
        uses_metric_singular=False,
        requires_time_column=True,
        max_groupby_dimensions=3,
        default_width=6,
    ),
    "echarts_timeseries_scatter": ChartTypeDescriptor(
        viz_type="echarts_timeseries_scatter",
        display_name="时序散点图",
        category="timeseries",
        description="用散点展示数据在时间轴上的分布",
        best_for=["时间轴上的数据分布", "离群值检测"],
        not_for=["精确趋势", "分类对比"],
        params=[
            ParamDescriptor(name="x_axis", type="string", required=True, description="X轴列名"),
            ParamDescriptor(name="metrics", type="metric_array", required=True, description="Y轴指标列表"),
            ParamDescriptor(name="groupby", type="string_array", required=False, description="分组列（不同颜色点）", default=[]),
        ],
        example_form_data={"x_axis": "date_col", "metrics": ["SUM(value)"], "groupby": []},
        uses_metric_singular=False,
        requires_time_column=False,
        max_groupby_dimensions=3,
        default_width=6,
    ),
    # ── 分类类 ──────────────────────────────────────────────
    "pie": ChartTypeDescriptor(
        viz_type="pie",
        display_name="饼图/环形图",
        category="categorical",
        description="展示各部分占整体的比例关系",
        best_for=["占比分析", "分类比例", "Top-N 分布"],
        not_for=["时间趋势", "超过 10 个类别", "精确数值对比"],
        params=[
            ParamDescriptor(name="metric", type="metric", required=True, description="定义扇形大小的单个指标"),
            ParamDescriptor(name="groupby", type="string_array", required=True, description="定义扇形标签的列"),
            ParamDescriptor(name="row_limit", type="integer", required=False, description="最大行数", default=100),
        ],
        example_form_data={"metric": "SUM(value)", "groupby": ["category"], "row_limit": 100},
        uses_metric_singular=True,
        requires_time_column=False,
        max_groupby_dimensions=1,
        advanced_params_schema={
            "innerRadius": {"type": "number", "range": [0.1, 0.8], "default": 0, "description": "环形图内圆半径比（0=实心饼图）"},
            "show_legend": {"type": "boolean", "default": True},
        },
    ),
    "funnel": ChartTypeDescriptor(
        viz_type="funnel",
        display_name="漏斗图",
        category="categorical",
        description="展示流程各阶段的转化率和流失情况",
        best_for=["转化漏斗", "流程分析", "阶段对比"],
        not_for=["时间趋势", "占比分析", "无序数据"],
        params=[
            ParamDescriptor(name="groupby", type="string_array", required=True, description="阶段名称列"),
            ParamDescriptor(name="metric", type="metric", required=True, description="各阶段数值指标"),
            ParamDescriptor(name="row_limit", type="integer", required=False, description="最大行数", default=100),
        ],
        example_form_data={"groupby": ["stage"], "metric": "SUM(count)", "row_limit": 100},
        uses_metric_singular=True,
        requires_time_column=False,
        max_groupby_dimensions=1,
    ),
    "radar": ChartTypeDescriptor(
        viz_type="radar",
        display_name="雷达图",
        category="categorical",
        description="多维度指标对比，适合展示综合能力画像",
        best_for=["多维度对比", "能力画像", "综合评价"],
        not_for=["时间趋势", "单一指标", "大量数据"],
        params=[
            ParamDescriptor(name="metrics", type="metric_array", required=True, description="各维度指标列表"),
            ParamDescriptor(name="groupby", type="string_array", required=True, description="对比实体列"),
        ],
        example_form_data={"metrics": ["SUM(score_a)", "SUM(score_b)", "SUM(score_c)"], "groupby": ["name"]},
        uses_metric_singular=False,
        requires_time_column=False,
        max_groupby_dimensions=2,
    ),
    "treemap_v2": ChartTypeDescriptor(
        viz_type="treemap_v2",
        display_name="矩形树图",
        category="categorical",
        description="用嵌套矩形展示层级数据的占比关系",
        best_for=["层级占比", "文件/预算分析", "多级分类"],
        not_for=["时间趋势", "精确数值"],
        params=[
            ParamDescriptor(name="metrics", type="metric_array", required=True, description="数值指标列表"),
            ParamDescriptor(name="groupby", type="string_array", required=True, description="层级列（从外到内）"),
        ],
        example_form_data={"metrics": ["SUM(value)"], "groupby": ["level1", "level2"]},
        uses_metric_singular=False,
        requires_time_column=False,
        max_groupby_dimensions=3,
    ),
    "sunburst_v2": ChartTypeDescriptor(
        viz_type="sunburst_v2",
        display_name="旭日图",
        category="categorical",
        description="用环形嵌套展示层级数据的占比，比矩形树图更直观",
        best_for=["层级占比可视化", "组织架构", "分类钻取"],
        not_for=["时间趋势", "精确数值", "扁平数据"],
        params=[
            ParamDescriptor(name="metrics", type="metric_array", required=True, description="数值指标列表"),
            ParamDescriptor(name="groupby", type="string_array", required=True, description="层级列（从内到外）"),
        ],
        example_form_data={"metrics": ["SUM(value)"], "groupby": ["level1", "level2"]},
        uses_metric_singular=False,
        requires_time_column=False,
        max_groupby_dimensions=3,
    ),
    # ── KPI 类 ──────────────────────────────────────────────
    "big_number_total": ChartTypeDescriptor(
        viz_type="big_number_total",
        display_name="大数字",
        category="kpi",
        description="展示单个关键指标的聚合值",
        best_for=["KPI 展示", "总计/平均值", "核心指标"],
        not_for=["趋势", "分类对比", "多指标"],
        params=[
            ParamDescriptor(name="metric", type="metric", required=True, description="单个指标"),
        ],
        example_form_data={"metric": "SUM(value)"},
        uses_metric_singular=True,
        requires_time_column=False,
        max_groupby_dimensions=0,
        default_width=3,
    ),
    "big_number": ChartTypeDescriptor(
        viz_type="big_number",
        display_name="大数字+趋势线",
        category="kpi",
        description="展示单个关键指标 + 迷你趋势线",
        best_for=["KPI + 趋势", "带背景的指标展示"],
        not_for=["分类对比", "多指标"],
        params=[
            ParamDescriptor(name="metric", type="metric", required=True, description="单个指标"),
            ParamDescriptor(name="granularity_sqla", type="string", required=True, description="时间列名"),
            ParamDescriptor(name="time_range", type="string", required=False, description="时间范围", default="100 years ago : now"),
        ],
        example_form_data={"metric": "SUM(value)", "granularity_sqla": "date_col", "time_range": "100 years ago : now"},
        uses_metric_singular=True,
        requires_time_column=True,
        max_groupby_dimensions=0,
        default_width=3,
    ),
    "gauge_chart": ChartTypeDescriptor(
        viz_type="gauge_chart",
        display_name="仪表盘",
        category="kpi",
        description="用仪表盘样式展示单个指标的完成度",
        best_for=["目标完成度", "百分比指标", "速率展示"],
        not_for=["分类对比", "时间趋势", "多指标"],
        params=[
            ParamDescriptor(name="metric", type="metric", required=True, description="单个指标"),
        ],
        example_form_data={"metric": "AVG(satisfaction)"},
        uses_metric_singular=True,
        requires_time_column=False,
        max_groupby_dimensions=0,
        default_width=3,
    ),
    # ── 表格类 ──────────────────────────────────────────────
    "table": ChartTypeDescriptor(
        viz_type="table",
        display_name="数据表",
        category="tabular",
        description="以表格形式展示数据，支持排序和分页",
        best_for=["详细数据展示", "多维度聚合", "数据导出"],
        not_for=["趋势可视化", "占比可视化"],
        params=[
            ParamDescriptor(name="metrics", type="metric_array", required=True, description="数值指标列表"),
            ParamDescriptor(name="groupby", type="string_array", required=True, description="维度列"),
            ParamDescriptor(name="row_limit", type="integer", required=False, description="最大行数", default=100),
        ],
        example_form_data={"metrics": ["SUM(value)"], "groupby": ["category"], "row_limit": 100},
        uses_metric_singular=False,
        requires_time_column=False,
        max_groupby_dimensions=0,
        default_width=12,
    ),
    "pivot_table_v2": ChartTypeDescriptor(
        viz_type="pivot_table_v2",
        display_name="透视表",
        category="tabular",
        description="交叉分析表，行和列均为维度",
        best_for=["交叉分析", "多维度汇总", "矩阵展示"],
        not_for=["趋势可视化", "大数据量"],
        params=[
            ParamDescriptor(name="metrics", type="metric_array", required=True, description="数值指标列表"),
            ParamDescriptor(name="groupby", type="string_array", required=True, description="行维度列"),
            ParamDescriptor(name="columns", type="string_array", required=False, description="列维度列", default=[]),
        ],
        example_form_data={"metrics": ["SUM(value)"], "groupby": ["row_dim"], "columns": ["col_dim"]},
        uses_metric_singular=False,
        requires_time_column=False,
        max_groupby_dimensions=0,
        default_width=12,
    ),
    # ── 分布类 ──────────────────────────────────────────────
    "histogram_v2": ChartTypeDescriptor(
        viz_type="histogram_v2",
        display_name="直方图",
        category="distribution",
        description="展示数值列的频率分布",
        best_for=["数据分布", "频率统计", "正态性检验"],
        not_for=["分类对比", "时间趋势"],
        params=[
            ParamDescriptor(name="column", type="string", required=True, description="数值列名"),
            ParamDescriptor(name="groupby", type="string_array", required=False, description="分组列", default=[]),
        ],
        example_form_data={"column": "age", "groupby": []},
        uses_metric_singular=False,
        requires_time_column=False,
        max_groupby_dimensions=1,
    ),
    "box_plot": ChartTypeDescriptor(
        viz_type="box_plot",
        display_name="箱线图",
        category="distribution",
        description="展示数据的统计分布（中位数、四分位、离群值）",
        best_for=["数据分布对比", "离群值检测", "统计概要"],
        not_for=["时间趋势", "精确数值"],
        params=[
            ParamDescriptor(name="metrics", type="metric_array", required=True, description="数值指标列表"),
            ParamDescriptor(name="groupby", type="string_array", required=False, description="分组列", default=[]),
        ],
        example_form_data={"metrics": ["SUM(value)"], "groupby": ["category"]},
        uses_metric_singular=False,
        requires_time_column=False,
        max_groupby_dimensions=2,
    ),
    "waterfall": ChartTypeDescriptor(
        viz_type="waterfall",
        display_name="瀑布图",
        category="distribution",
        description="展示数值的增减变化过程，适合财务分析",
        best_for=["增减分析", "贡献度", "财务瀑布"],
        not_for=["时间趋势（用折线）", "占比分析"],
        params=[
            ParamDescriptor(name="x_axis", type="string", required=True, description="X轴列名"),
            ParamDescriptor(name="metrics", type="metric_array", required=True, description="数值指标列表"),
        ],
        example_form_data={"x_axis": "category", "metrics": ["SUM(value)"]},
        uses_metric_singular=False,
        requires_time_column=False,
        max_groupby_dimensions=0,
    ),
    # ── 关系类 ──────────────────────────────────────────────
    "sankey_v2": ChartTypeDescriptor(
        viz_type="sankey_v2",
        display_name="桑基图",
        category="relationship",
        description="展示数据从源头到目标的流量和转化",
        best_for=["流量分析", "转化路径", "资源流向"],
        not_for=["时间趋势", "简单分类对比"],
        params=[
            ParamDescriptor(name="source", type="string_array", required=True, description="来源列"),
            ParamDescriptor(name="target", type="string_array", required=True, description="目标列"),
            ParamDescriptor(name="metric", type="metric", required=True, description="流量指标"),
        ],
        example_form_data={"source": ["from_node"], "target": ["to_node"], "metric": "SUM(flow)"},
        uses_metric_singular=True,
        requires_time_column=False,
        max_groupby_dimensions=0,
    ),
    "heatmap_v2": ChartTypeDescriptor(
        viz_type="heatmap_v2",
        display_name="热力图",
        category="relationship",
        description="用颜色深浅展示两个维度交叉处的数值",
        best_for=["交叉矩阵", "相关性分析", "日历热力"],
        not_for=["单一维度", "精确数值"],
        params=[
            ParamDescriptor(name="x_axis", type="string", required=True, description="X轴列名"),
            ParamDescriptor(name="y_axis", type="string", required=True, description="Y轴列名"),
            ParamDescriptor(name="metric", type="metric", required=True, description="数值指标"),
        ],
        example_form_data={"x_axis": "day_of_week", "y_axis": "hour", "metric": "SUM(count)"},
        uses_metric_singular=True,
        requires_time_column=False,
        max_groupby_dimensions=0,
    ),
    "graph_chart": ChartTypeDescriptor(
        viz_type="graph_chart",
        display_name="网络图",
        category="relationship",
        description="展示节点之间的连接关系",
        best_for=["关系网络", "社交图谱", "依赖关系"],
        not_for=["时间趋势", "简单分类"],
        params=[
            ParamDescriptor(name="source", type="string_array", required=True, description="源节点列"),
            ParamDescriptor(name="target", type="string_array", required=True, description="目标节点列"),
            ParamDescriptor(name="metric", type="metric", required=True, description="边的权重指标"),
        ],
        example_form_data={"source": ["from_id"], "target": ["to_id"], "metric": "SUM(weight)"},
        uses_metric_singular=True,
        requires_time_column=False,
        max_groupby_dimensions=0,
    ),
    # ── 多维类 ──────────────────────────────────────────────
    "bubble_v2": ChartTypeDescriptor(
        viz_type="bubble_v2",
        display_name="气泡图",
        category="multidimensional",
        description="用X轴、Y轴和气泡大小展示三维数据关系",
        best_for=["三维关系", "多变量对比", "矩阵分析"],
        not_for=["时间趋势", "单维度数据"],
        params=[
            ParamDescriptor(name="series", type="string", required=True, description="系列/分组列"),
            ParamDescriptor(name="entity", type="string", required=True, description="实体标识列"),
            ParamDescriptor(name="x", type="metric", required=True, description="X轴指标"),
            ParamDescriptor(name="y", type="metric", required=True, description="Y轴指标"),
            ParamDescriptor(name="size", type="metric", required=True, description="气泡大小指标"),
        ],
        example_form_data={"series": "region", "entity": "country", "x": "SUM(gdp)", "y": "AVG(life_exp)", "size": "SUM(population)"},
        uses_metric_singular=True,
        requires_time_column=False,
        max_groupby_dimensions=0,
    ),
    "mixed_timeseries": ChartTypeDescriptor(
        viz_type="mixed_timeseries",
        display_name="混合图",
        category="multidimensional",
        description="在同一个画布上混合折线图和柱状图",
        best_for=["多指标对比", "量价分析", "收入vs增长率"],
        not_for=["单指标", "分类对比"],
        params=[
            ParamDescriptor(name="metricsA", type="metric_array", required=True, description="A组指标（柱状图）"),
            ParamDescriptor(name="metricsB", type="metric_array", required=True, description="B组指标（折线图）"),
            ParamDescriptor(name="groupbyA", type="string_array", required=False, description="A组分组列", default=[]),
            ParamDescriptor(name="groupbyB", type="string_array", required=False, description="B组分组列", default=[]),
            ParamDescriptor(name="granularity_sqla", type="string", required=True, description="时间列名"),
        ],
        example_form_data={"metricsA": ["SUM(revenue)"], "metricsB": ["AVG(growth_rate)"], "groupbyA": [], "groupbyB": [], "granularity_sqla": "date_col"},
        uses_metric_singular=False,
        requires_time_column=True,
        max_groupby_dimensions=2,
    ),
}
